### ISSUE TITLE
Wrongly formatted html

### ISSUE THREAD

**Issue by jsilvestre** [lemelon/cozysdk-client-tuto#2]
An user reported on IRC that https://github.com/cozy/cozysdk-client-tuto/blob/step1-angular/index.html was wrongly formatted html. It should be fixed to prevent misunderstandings.

**Comment by martinsam** [comment]
Index.html ->

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Your app !</title>
</head>
<body>
  <p>Hello World !<p>
</body>
</html>
```

**Comment by aenario** [comment]
This was fixed. Thanks @martinsam for reporting.
